### ISSUE TITLE
on window resize albums are duplicated

### ISSUE THREAD

**Issue by Fannii** [azcpavel/ExceptioGooglePlusImageGallery#1]
A solution:
                var id;
        $(window).resize(function(){
            clearTimeout(id);
            id = setTimeout(doneResizing, 500);
        });
        function doneResizing(){
            windowWidth = $(window).width();
            windowHeight = $(window).height();
            ex.reloadGallery(options);
        }

**Comment by azcpavel** [comment]
Thanks.

sorry i have added you name in the file
it's fixed now.
enjoy....
